name: docsort
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - opencv
  - flet
  - pip
  - scipy
  - transformers
  - sentencepiece
  - pydantic
  - click
  - langdetect
  - argostranslate
pip:
  - torch
  - torchvision
  - "python-doctr[torch]"
  - pydrive2
