name: docsort
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - opencv
  - flet
  - pip
  - scipy
  - transformers
  - pydantic
  - click
pip:
  - torch
  - torchvision
  - "python-doctr[torch]"
